### PR TITLE
Attempt to simplify glue unit converter for PR 2022 (try 2)

### PR DESCRIPTION
**Pull request by pllim**
Like #13 only now I remember to change the base lol. It's been a long day...

This is my attempt at simplifying the unit converter proposed in https://github.com/spacetelescope/jdaviz/pull/2022 .

I tried to follow https://docs.glueviz.org/en/stable/customizing_guide/units.html though I am not sure if I caught all the gotchas that you encountered. Please let me know. Thanks!

### CODE REVIEW

**Comment by javerbukh** [comment]
Were you able to add both data to the viewer?

**Comment by pllim** [comment]
@javerbukh , not initially via checkbox but I could see both after running one of the next cells. I don't know what is the expected behaviors here.

**Comment by javerbukh** [comment]
@pllim when I try to add both data I get the following traceback, even after running the following cells

<details>

```

---------------------------------------------------------------------------
TraitError                                Traceback (most recent call last)
File ~/miniconda3/envs/test_prs_2/lib/python3.9/site-packages/ipyvue/VueTemplateWidget.py:60, in Events._handle_event(self, _, content, buffers)
     58     getattr(self, "vue_" + event)(data, buffers)
     59 else:
---> 60     getattr(self, "vue_" + event)(data)

File ~/Documents/jdaviz_dev/jdaviz/jdaviz/app.py:1375, in Application.vue_data_item_visibility(self, event)
   1374 def vue_data_item_visibility(self, event):
-> 1375     self.set_data_visibility(event['id'],
   1376                              self._get_data_item_by_id(event['item_id'])['name'],
   1377                              visible=event['visible'], replace=event.get('replace', False))

File ~/Documents/jdaviz_dev/jdaviz/jdaviz/app.py:1415, in Application.set_data_visibility(self, viewer_reference, data_label, visible, replace)
   1409     raise ValueError(
   1410         f"No data item found with label '{data_label}'. Label must be one "
   1411         "of:\n\t" + "\n\t".join(dc_labels))
   1413 [data] = [x for x in self.data_collection if x.label == data_label]
-> 1415 viewer.add_data(data, percentile=95, color=viewer.color_cycler())
   1417 add_data_message = AddDataMessage(data, viewer,
   1418                                   viewer_id=viewer_id,
   1419                                   sender=self)
   1420 self.hub.broadcast(add_data_message)

File ~/Documents/jdaviz_dev/jdaviz/jdaviz/configs/specviz/plugins/viewers.py:353, in SpecvizProfileView.add_data(self, data, color, alpha, **layer_state)
    333 """
    334 Overrides the base class to add markers for plotting
    335 uncertainties and data quality flags.
   (...)
    349     `True` if successful, `False` otherwise.
    350 """
    351 # The base class handles the plotting of the main
    352 # trace representing the spectrum itself.
--> 353 result = super().add_data(data, color, alpha, **layer_state)
    355 self._plot_uncertainties()
    357 self._plot_mask()

File ~/miniconda3/envs/test_prs_2/lib/python3.9/site-packages/glue_jupyter/view.py:118, in IPyWidgetView.add_data(self, data, color, alpha, **layer_state)
    114 def add_data(self, data, color=None, alpha=None, **layer_state):
    116     data = validate_data_argument(self._data, data)
--> 118     result = super().add_data(data)
    120     if not result:
    121         return

File ~/miniconda3/envs/test_prs_2/lib/python3.9/site-packages/glue/viewers/common/viewer.py:207, in Viewer.add_data(self, data)
    203     raise IncompatibleDataException("Data not in DataCollection")
    205 # Create layer artist and add to container. First check whether any
    206 # plugins want to make a custom layer artist.
--> 207 layer = get_layer_artist_from_registry(data, self) or self.get_data_layer_artist(data)
    209 if layer is None:
    210     return False

File ~/miniconda3/envs/test_prs_2/lib/python3.9/site-packages/glue/viewers/common/viewer.py:238, in Viewer.get_data_layer_artist(self, layer, layer_state)
    237 def get_data_layer_artist(self, layer=None, layer_state=None):
--> 238     return self.get_layer_artist(self._data_artist_cls, layer=layer, layer_state=layer_state)

File ~/miniconda3/envs/test_prs_2/lib/python3.9/site-packages/glue_jupyter/view.py:143, in IPyWidgetView.get_layer_artist(self, cls, layer, layer_state)
    142 def get_layer_artist(self, cls, layer=None, layer_state=None):
--> 143     return cls(self, self.state, layer=layer, layer_state=layer_state)

File ~/miniconda3/envs/test_prs_2/lib/python3.9/site-packages/glue_jupyter/bqplot/profile/layer_artist.py:31, in BqplotProfileLayerArtist.__init__(self, view, viewer_state, layer_state, layer)
     29 def __init__(self, view, viewer_state, layer_state=None, layer=None):
---> 31     super().__init__(viewer_state, layer_state=layer_state, layer=layer)
     33     # Watch for changes in the viewer state which would require the
     34     # layers to be redrawn
     35     self._viewer_state.add_global_callback(self._update_profile)

File ~/miniconda3/envs/test_prs_2/lib/python3.9/site-packages/glue/viewers/common/layer_artist.py:29, in LayerArtist.__init__(self, viewer_state, layer_state, layer)
     25 self.state = layer_state or self._layer_state_cls(viewer_state=viewer_state,
     26                                                   layer=self.layer)
     28 if self.state not in self._viewer_state.layers:
---> 29     self._viewer_state.layers.append(self.state)
     31 self.zorder = self.state.zorder
     32 self.visible = self.state.visible

File ~/miniconda3/envs/test_prs_2/lib/python3.9/site-packages/echo/containers.py:52, in CallbackList.append(self, value)
     50 def append(self, value):
     51     super(CallbackList, self).append(self._prepare_add(value))
---> 52     self.notify_all()

File ~/miniconda3/envs/test_prs_2/lib/python3.9/site-packages/echo/containers.py:45, in CallbackList.notify_all(self, *args, **kwargs)
     43 def notify_all(self, *args, **kwargs):
     44     for callback in self.callbacks:
---> 45         callback(*args, **kwargs)

File ~/miniconda3/envs/test_prs_2/lib/python3.9/site-packages/echo/containers.py:166, in dynamic_callback.__call__(self, *args, **kwargs)
    165 def __call__(self, *args, **kwargs):
--> 166     self.function(*args, **kwargs)

File ~/miniconda3/envs/test_prs_2/lib/python3.9/site-packages/echo/containers.py:189, in ListCallbackProperty._default_setter.<locals>.callback(*args, **kwargs)
    188 def callback(*args, **kwargs):
--> 189     self.notify(instance, wrapped_list, wrapped_list)

File ~/miniconda3/envs/test_prs_2/lib/python3.9/site-packages/echo/core.py:125, in CallbackProperty.notify(self, instance, old, new)
    123     return
    124 for cback in self._callbacks.get(instance, []):
--> 125     cback(new)
    126 for cback in self._2arg_callbacks.get(instance, []):
    127     cback(old, new)

File ~/Documents/jdaviz_dev/jdaviz/jdaviz/configs/default/plugins/viewers.py:169, in JdavizViewerMixin._on_layers_update(self, layers)
    167 if layer_info not in self._layers_with_defaults_applied:
    168     self._layers_with_defaults_applied.append(layer_info)
--> 169     self._apply_layer_defaults(layer)
    171 if layer.layer.label in expected_subset_layers:
    172     if layer.layer.label in self._expected_subset_layers:

File ~/Documents/jdaviz_dev/jdaviz/jdaviz/configs/default/plugins/viewers.py:65, in JdavizViewerMixin._apply_layer_defaults(self, layer_state)
     62     layer_state.as_steps = self._get_layer(layer_state.layer.data.label).as_steps
     63 else:
     64     # default to not plotting with as_steps (despite glue defaulting to True)
---> 65     layer_state.as_steps = False
     66 # whenever as_steps changes, we need to redraw the uncertainties (if enabled)
     67 layer_state.add_callback('as_steps', self._show_uncertainty_changed)

File ~/miniconda3/envs/test_prs_2/lib/python3.9/site-packages/echo/core.py:263, in HasCallbackProperties.__setattr__(self, attribute, value)
    261 super(HasCallbackProperties, self).__setattr__(attribute, value)
    262 if self.is_callback_property(attribute):
--> 263     self._notify_global(**{attribute: value})

File ~/miniconda3/envs/test_prs_2/lib/python3.9/site-packages/glue/utils/matplotlib.py:181, in defer_draw.<locals>.wrapper(*args, **kwargs)
    177 @wraps(func)
    178 def wrapper(*args, **kwargs):
    180     if len(DEFER_DRAW_BACKENDS) == 0:
--> 181         return func(*args, **kwargs)
    183     # Don't recursively defer draws. We just check the first draw_idle
    184     # method since all should be modified in sync.
    185     if isinstance(DEFER_DRAW_BACKENDS[0].draw_idle, DeferredMethod):

File ~/miniconda3/envs/test_prs_2/lib/python3.9/site-packages/glue/viewers/matplotlib/state.py:293, in MatplotlibLayerState._notify_global(self, *args, **kwargs)
    291 @defer_draw
    292 def _notify_global(self, *args, **kwargs):
--> 293     super(MatplotlibLayerState, self)._notify_global(*args, **kwargs)

File ~/miniconda3/envs/test_prs_2/lib/python3.9/site-packages/echo/core.py:258, in HasCallbackProperties._notify_global(self, **kwargs)
    256 if len(kwargs) > 0:
    257     for callback in self._global_callbacks:
--> 258         callback(**kwargs)

File ~/miniconda3/envs/test_prs_2/lib/python3.9/site-packages/echo/containers.py:45, in CallbackList.notify_all(self, *args, **kwargs)
     43 def notify_all(self, *args, **kwargs):
     44     for callback in self.callbacks:
---> 45         callback(*args, **kwargs)

File ~/miniconda3/envs/test_prs_2/lib/python3.9/site-packages/echo/containers.py:166, in dynamic_callback.__call__(self, *args, **kwargs)
    165 def __call__(self, *args, **kwargs):
--> 166     self.function(*args, **kwargs)

File ~/miniconda3/envs/test_prs_2/lib/python3.9/site-packages/echo/containers.py:189, in ListCallbackProperty._default_setter.<locals>.callback(*args, **kwargs)
    188 def callback(*args, **kwargs):
--> 189     self.notify(instance, wrapped_list, wrapped_list)

File ~/miniconda3/envs/test_prs_2/lib/python3.9/site-packages/echo/core.py:125, in CallbackProperty.notify(self, instance, old, new)
    123     return
    124 for cback in self._callbacks.get(instance, []):
--> 125     cback(new)
    126 for cback in self._2arg_callbacks.get(instance, []):
    127     cback(old, new)

File ~/Documents/jdaviz_dev/jdaviz/jdaviz/configs/imviz/plugins/coords_info/coords_info.py:64, in CoordsInfo._create_viewer_callbacks.<locals>.<lambda>(msg)
     61 callback = self._viewer_callback(viewer, self._viewer_mouse_event)
     62 viewer.add_event_callback(callback, events=['mousemove', 'mouseleave', 'mouseenter'])
---> 64 viewer.state.add_callback('layers', lambda msg: self._layers_changed(viewer))

File ~/Documents/jdaviz_dev/jdaviz/jdaviz/configs/imviz/plugins/coords_info/coords_info.py:146, in CoordsInfo._layers_changed(self, viewer)
    142     return
    144 # update display for a (possible) change to the active layer based on the last known
    145 # cursor position
--> 146 self.update_display(viewer, self._x, self._y)

File ~/Documents/jdaviz_dev/jdaviz/jdaviz/configs/imviz/plugins/coords_info/coords_info.py:150, in CoordsInfo.update_display(self, viewer, x, y)
    148 def update_display(self, viewer, x, y):
    149     if isinstance(viewer, SpecvizProfileView):
--> 150         self._spectrum_viewer_update(viewer, x, y)
    151     elif isinstance(viewer,
    152                     (ImvizImageView, CubevizImageView, MosvizImageView, MosvizProfile2DView)):
    153         self._image_viewer_update(viewer, x, y)

File ~/Documents/jdaviz_dev/jdaviz/jdaviz/configs/imviz/plugins/coords_info/coords_info.py:365, in CoordsInfo._spectrum_viewer_update(self, viewer, x, y)
    362 self.row3_title = 'Flux'
    363 self.row3_text = f'{closest_flux.value:10.5e} {closest_flux.unit.to_string()}'
--> 365 self.icon = closest_icon
    367 self.marks[viewer._reference_id].update_xy([closest_wave.value], [closest_flux.value])  # noqa
    368 self.marks[viewer._reference_id].visible = True

File ~/miniconda3/envs/test_prs_2/lib/python3.9/site-packages/traitlets/traitlets.py:732, in TraitType.__set__(self, obj, value)
    730     raise TraitError('The "%s" trait is read-only.' % self.name)
    731 else:
--> 732     self.set(obj, value)

File ~/miniconda3/envs/test_prs_2/lib/python3.9/site-packages/traitlets/traitlets.py:706, in TraitType.set(self, obj, value)
    705 def set(self, obj, value):
--> 706     new_value = self._validate(obj, value)
    707     try:
    708         old_value = obj._trait_values[self.name]

File ~/miniconda3/envs/test_prs_2/lib/python3.9/site-packages/traitlets/traitlets.py:738, in TraitType._validate(self, obj, value)
    736     return value
    737 if hasattr(self, "validate"):
--> 738     value = self.validate(obj, value)
    739 if obj._cross_validation_lock is False:
    740     value = self._cross_validate(obj, value)

File ~/miniconda3/envs/test_prs_2/lib/python3.9/site-packages/traitlets/traitlets.py:2536, in Unicode.validate(self, obj, value)
   2534         msg = "Could not decode {!r} for unicode trait '{}' of {} instance."
   2535         raise TraitError(msg.format(value, self.name, class_of(obj))) from e
-> 2536 self.error(obj, value)

File ~/miniconda3/envs/test_prs_2/lib/python3.9/site-packages/traitlets/traitlets.py:844, in TraitType.error(self, obj, value, error, info)
    838 else:
    839     e = "The '{}' trait expected {}, not {}.".format(
    840         self.name,
    841         self.info(),
    842         describe("the", value),
    843     )
--> 844 raise TraitError(e)

TraitError: The 'icon' trait of a CoordsInfo instance expected a unicode string, not the NoneType None.
```

</details>

**Comment by pllim** [comment]
Okay, I saw that too but I wasn't sure if it was something expected or not. Good to know it's not expected. I'll dig.

**Pull request closed without merging**
